### ISSUE TITLE
Yanked crates return 403 but is not checked

### ISSUE THREAD

**Issue by pinkforest** [evanrichter/crate-mirror#1]
### Background

hey thanks for working on tools like this :purple_heart: 

I went thru the report at crates-io-team discord - many thanks for that too :unicorn: 

As a result I raised couple of issues around I could see what was going wrong elsewhere

I found them with:

https://github.com/pinkforest/crates.io-duplicates

First crates-index crate should perhaps validate Index and not offer conflicting checksums / duplicate versions -

https://github.com/frewsxcv/rust-crates-index/issues/73

And then crates.io-index should perhaps hold integrity and perhaps should clean existing entries up

https://github.com/rust-lang/crates.io/issues/4418

There was however an error that crate-mirror should handle and I thought to share this with you

### Yanked Status

Since the response HTTP error code is not checked

e.g. on the list was glue-0.8.3

https://static.crates.io/crates/glue/glue-0.8.3.crate

As you can see its' returning error

$ wget https://static.crates.io/crates/glue/glue-0.8.3.crate
--2022-01-08 21:19:59--  https://static.crates.io/crates/glue/glue-0.8.3.crate
Resolving static.crates.io (static.crates.io)... 2600:9000:2212:9c00:1b:d7a6:ee00:93a1, 2600:9000:2212:7800:1b:d7a6:ee00:93a1, 2600:9000:2212:1200:1b:d7a6:ee00:93a1, ...
Connecting to static.crates.io (static.crates.io)|2600:9000:2212:9c00:1b:d7a6:ee00:93a1|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-01-08 21:20:00 ERROR 403: Forbidden.

But this isn't checked on the mirror

Index has yanked true/false status which perhaps should be checked.

The index here:
https://github.com/rust-lang/crates.io-index/blob/master/gl/ue/glue

`{"name":"glue","vers":"0.8.3","deps":[{"name":"bork","req":"^0.2","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"paste","req":"^0.1","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"}],"cksum":"c10b6e678c51deb0e885e33bfe56cef065155f1c709d33777db53f0859668118","features":{},"yanked":true,"links":null}`

### Expected Behavior

- [ ] 403 Error is handled
- [ ] Yanked status is handled

**Comment by evanrichter** [comment]
thank you very much!
